version: '3.8'

services:
  circle-platform:
    build: .
    ports:
      - "8060:8060"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/"]
      interval: 30s
      timeout: 10s
      retries: 3
