source 'https://rubygems.org'

gem 'rails', '~> 7.1.3'
gem 'sqlite3', '~> 1.7'
gem 'puma', '~> 6.4'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development do
  gem 'listen', '~> 3.8'
  gem 'debug'
end
